extends: '@danny.andrews/eslint-config'
rules:
  no-underscore-dangle:
    - error
    - allow:
      - __
  # Remove once http://tinyurl.com/yayyweu3 is fixed.
  import/no-extraneous-dependencies: off
env:
  node: true
  browser: false
