extends: '@danny.andrews/eslint-config'
rules:
  # Move to my config
  no-restricted-syntax:
    - error
    - AwaitExpression
  max-params:
    - error
    - 3

  no-underscore-dangle:
    - error
    - allow:
      - __
  # Remove once http://tinyurl.com/yayyweu3 is fixed.
  import/no-extraneous-dependencies: off
env:
  node: true
  browser: false
