version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    environment:
      - CIRCLE_ARTIFACTS: ./example/dist/artifacts
    steps:
      - checkout
      - run: yarn install
      - run: yarn ci
      - run: yarn build
      - run: yarn build:example
      - run: './circleci-weigh-in -- --stats-filepath=example/dist/stats.json --project-name="circleci-weigh-in" --failure-thresholds="[{ \"targets\": \".js\", \"maxSize\": 7, \"strategy\": "all" }]"'
      - store_artifacts:
          path: ./example/dist/artifacts
          destination: ./
