version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.0
    environment:
      - CIRCLE_ARTIFACTS: ./example/dist/artifacts
    steps:
      - checkout
      - run: yarn install
      - run: yarn ci
      - run: yarn build
      - run: yarn build:example
      - run: './circleci-weigh-in -- --manifest-filepath=example/dist/manifest.json --output-directory=example/dist --project-name=circleci-weigh-in --failure-thresholds="[{ \"targets\": \".js\", \"maxSize\": 20000, \"strategy\": \"total\" }]"'
      - store_artifacts:
          path: ./example/dist/artifacts
          destination: ./
