version: 2
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    environment:
      - CIRCLE_ARTIFACTS: ./example/dist/artifacts
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: yarn ci
      - run: ./thresh
      - store_artifacts:
          path: ./example/dist/artifacts
          destination: ./
